### ISSUE TITLE
Issue with installing on MacOS

### ISSUE THREAD

**Issue by katossky** [r-lib/bench#109]
(I really do not understand what is happening here, so please be kind and patient.)

There seem to be an issue when installing bench on MacOS.

When I install from binary, I get the message:

```
Erreur : package or namespace load failed for ‘bench’ in dyn.load(file, DLLpath = DLLpath, ...):
 impossible de charger l'objet partagé '/Users/arthur/Library/R/4.0/library/bench/libs/bench.so':
  dlopen(/Users/arthur/Library/R/4.0/library/bench/libs/bench.so, 6): Library not loaded: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libR.dylib
  Referenced from: /Users/arthur/Library/R/4.0/library/bench/libs/bench.so
  Reason: image not found
```

... which is normal since on my Mac R `libR.dylib` is installed at `/usr/local/bin/R/lib/libR.dylib`.

When I install from source I get an other error message:

```
Erreur : package or namespace load failed for ‘bench’ in get(Info[i, 1], envir = env):
 lazy-load database '/Users/arthur/Library/R/4.0/library/bench/R/bench.rdb' is corrupt
De plus : Warning message:
In get(Info[i, 1], envir = env) : internal error -3 in R_decompress1
```

I have no idea what is happening, and a 2-hours long search on the Internet did not help.

- R was installed via Brew and is version 4.0.4.
- I tried to use renv in a new projet, and `bench` temporarily worked, but stopped after I installed a couple of other libraries

Any clue?

**Comment by jimhester** [comment]
Unfortunately, when R is installed by homebrew in this way it is not compatible with the CRAN package binaries, which means you must build and install all packages from source. This takes additional time during installation and can lead to more time spent dealing with installation issues if a package fails to compile, as you seem to have encountered.

Instead, if you prefer the convenience of homebrew, we recommend installing the R cask.

You can install it by first removing your existing build of R with `brew uninstall r` and then installing the cask. e.g. `brew install --cask r`, _not_ `brew install r`.

This will allow you to use the pre-build package binaries from CRAN and should remove most of your problems.

The second error occurs because you have the bench package already loaded in your R session when you tried to install it.

I don't believe any of these errors are specific to the bench package, and generally you will receive better help for system configuration questions at <https://community.rstudio.com>. Would you mind asking any further questions related to R configurations over there?

**Comment by katossky** [comment]
Thank you for your politeness and your time. I indeed feared it was not so much `bench` related. Thank you a lot.
