### ISSUE TITLE
Explain what `n_gc` signifies

### ISSUE THREAD

**Issue by HughParsonage** [r-lib/bench#24]
The addition of `n_gc` is very welcome, but I think the documentation lacks a sentence or two explaining what this value signifies, or what users should pay attention to. For example, should I favour expressions with low `n_gc`? Should I only make comparisons between expressions with the same value of `n_gc`?

**Comment by aadler** [comment]
It's a better way of addressing the problem Radford Neil had with [microbenchmark](https://github.com/joshuaulrich/microbenchmark). See [his post](https://radfordneal.wordpress.com/2014/02/02/inaccurate-results-from-microbenchmark/) from 2014. The filtering mechanism is not only because you can benchmark raw execution times, but because otherwise comparable calls which, through their memory use, trigger more common garbage collections should probably be optimized if possible, avoided if not.
