### ISSUE TITLE
Warn instead of Error when `check` Fails?

### ISSUE THREAD

**Issue by brodieG** [r-lib/bench#53]
Why not allow the bench::mark to return the results and indicate that the expressions produced unequal output either via a warning or annotation?  I was just playing with the package with some slow bench marks and I waited a while to get an error and no times for something I did not expect to be equal (attribute diffs in my case).  Obviously I can implement this as a function to pass to check, but I never remember that check defaults to TRUE _and_ errors.

`warning(..., immediate.=TRUE)` will also allow the user to abort if they did expect the expressions to be `all.equal`.

Not a big deal and I primarily use other bench marking tools, but wanted to suggest this in case it resonated with other users and you guys.  I'm having a hard time thinking of a case where a hard error that throws away the data from the first timing / memory pass is preferable.

**Comment by jimhester** [comment]
I sympathize for the lost time.

There are almost certainly many unknowingly invalid benchmarks with other benchmarking tools which do not verify the results are consistent by default. It is too easy to ignore warnings, so I think it is important for users to address it explicitly if they do want to accept inconsistent results. You can always use `check = FALSE` if you want to disable checking entirely, or as you said something like 

```r
check = function(x, y) { 
  res <- all.equal(x, y)
  if (!isTRUE(res)) {
    warning(res, call. = FALSE)
  }
  TRUE
}
```

if you want warnings instead of errors.

**Comment by brodieG** [comment]
Obviously we see things a little differently, and that's perfectly fine :).  Just wanted to make sure this wasn't a case you hadn't run into / considered.  Thanks for the thoughtful response.
