### ISSUE TITLE
min_iterations not met

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/bench#81]
```
library(data.table) # Rdatatable/data.table@psum, you can probably replace ptest with pany again?

NN = 1e7

JJ = 20L

ll = lapply(integer(JJ), function(x) sample(-2:2, NN, TRUE))

bench::mark(
  do.call(pany, ll),
  do.call(ptest, ll),
  min_iterations = 10L
)
# # A tibble: 2 x 13
#   expression           min median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result memory
#   <bch:expr>         <bch> <bch:>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list> <list>
# 1 do.call(pany, ll)  719ms  733ms      1.36    38.1MB    0.151     9     1      6.61s <lgl … <Rpro…
# 2 do.call(ptest, ll) 184ms  203ms      4.93    38.1MB    0        10     0      2.03s <lgl … <Rpro…
# # … with 2 more variables: time <list>, gc <list>
```

It doesn't happen every time, but often one of the expressions will run `< min_iterations` times.

**Comment by jimhester** [comment]
`min_iterations` are the total number of iterations that are run. However iterations with garbage collections in them are filtered out before the results are displayed, which is why `n_itr` is less than 10 in this example. You can use `bench::mark(filter_gc = FALSE)` to disable this filtering up front if it is more appropriate to your particular benchmark. Alternatively you can call `summary(, filter_gc = FALSE)` to get the unfiltered output after the fact.

``` r
NN <- 1e5
JJ = 20L
ll = lapply(integer(JJ), function(x) sample(-2:2, NN, TRUE))
x <- bench::mark(vapply(ll, any, logical(1)), min_iterations = 200)
x[["n_itr"]]
#> [1] 169
summary(x, filter_gc = FALSE)[["n_itr"]]
#> [1] 200
```

<sup>Created on 2020-05-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
